name = "MGPipsSolver"
uuid = "0e2b999c-8a3a-11ea-3c4b-c36350f324a0"
authors = ["Jordan Jalving", "University of Wisconsin-Madison"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
